-- AlterTable
ALTER TABLE "Quote" ADD COLUMN     "assumptions" TEXT,
ADD COLUMN     "clientAddress" TEXT,
ADD COLUMN     "clientCompany" TEXT,
ADD COLUMN     "clientEmail" TEXT,
ADD COLUMN     "clientName" TEXT,
ADD COLUMN     "clientObligations" TEXT,
ADD COLUMN     "clientPhone" TEXT,
ADD COLUMN     "clientSignature" TEXT,
ADD COLUMN     "clientSignedAt" TIMESTAMP(3),
ADD COLUMN     "clientSignedBy" TEXT,
ADD COLUMN     "companyAddress" TEXT,
ADD COLUMN     "companyEmail" TEXT,
ADD COLUMN     "companyLogo" TEXT,
ADD COLUMN     "companyName" TEXT,
ADD COLUMN     "companyPhone" TEXT,
ADD COLUMN     "companyWebsite" TEXT,
ADD COLUMN     "confidentialityClause" TEXT,
ADD COLUMN     "contactPerson" TEXT,
ADD COLUMN     "currency" TEXT DEFAULT 'USD',
ADD COLUMN     "depositAmount" DOUBLE PRECISION,
ADD COLUMN     "depositPercent" DOUBLE PRECISION,
ADD COLUMN     "discountType" TEXT,
ADD COLUMN     "exclusions" TEXT,
ADD COLUMN     "executiveSummary" TEXT,
ADD COLUMN     "freeSupportMonths" INTEGER DEFAULT 1,
ADD COLUMN     "includedRevisions" INTEGER DEFAULT 2,
ADD COLUMN     "internalNotes" TEXT,
ADD COLUMN     "ipRights" TEXT,
ADD COLUMN     "maintenanceTerms" TEXT,
ADD COLUMN     "paymentTerms" TEXT,
ADD COLUMN     "pricingItems" TEXT,
ADD COLUMN     "providerSignature" TEXT,
ADD COLUMN     "providerSignedAt" TIMESTAMP(3),
ADD COLUMN     "providerSignedBy" TEXT,
ADD COLUMN     "revisionCost" DOUBLE PRECISION,
ADD COLUMN     "revisionsPolicy" TEXT,
ADD COLUMN     "scopeOfWork" TEXT,
ADD COLUMN     "taxRate" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "validityDays" INTEGER NOT NULL DEFAULT 30,
ALTER COLUMN "subtotal" DROP NOT NULL,
ALTER COLUMN "tax" DROP NOT NULL,
ALTER COLUMN "discount" DROP NOT NULL,
ALTER COLUMN "total" DROP NOT NULL,
ALTER COLUMN "items" DROP NOT NULL,
ALTER COLUMN "designCost" DROP NOT NULL,
ALTER COLUMN "developmentCost" DROP NOT NULL,
ALTER COLUMN "monthlyHosting" DROP NOT NULL,
ALTER COLUMN "monthlyMaintenance" DROP NOT NULL,
ALTER COLUMN "monthlyRecurring" DROP NOT NULL,
ALTER COLUMN "setupFee" DROP NOT NULL,
ALTER COLUMN "yearlyRecurring" DROP NOT NULL;
